Goal: Aim of the study: Is there significant inter- and intra-individual variability in heat
flow measurements in each of the sensors? How are measurements from different
sensors related?
INTRA:
- Q1: How does heat flow change for the same person between day 1 and day 2?
- Q2: How does heat flow change between session 1 and session 4, doing the same activity?
INTER:
- Q3: How does heat flow change across participants, for same session, day, and activity? (note to self: look at gender)

# General takeaways before moving to R:
- There are six sensors
- There were 24 people (12M, 12F) who got measured over 2 days, 4 sessions per day.
- There were 3 activities (sitting, standing, walking)
- Since some people are missing HF value (NaN), need to account for that before analysis!
- Now, move to analysis in

Q0: are heat flow measures independent?
INTRA:
- Q1: How does heat flow change for the same person between day 1 and day 2, for the same session and activity??
- Q2: How does heat flow change between session 1 and session 4, doing the same activity?
INTER:
- Q3: How does heat flow change across participants, for same session, day, and activity? (note to self: look at gender)

In [9]:
#Section 1:
#Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
import os
import time

In [10]:
time_start=time.perf_counter()

In [11]:
#Set directory
cwd = os.getcwd()
print("Current working directory: {0}".format(cwd)) #figure out what directory we are in
project_dir = Path.cwd()
print("project directory: {0}".format(project_dir)) #set project directory to current working directory
#Load the dataset
file_path = os.path.join(project_dir, "heat_flow_ICE_EPFL.csv") #construct the file path to the dataset, which is in the "Analysis & Plots" folder within the project directory
df = pd.read_csv(file_path)

Current working directory: /Users/sunilmd/Desktop/vscode/MATH-516/project-2-nikita_zhuo/analysis_and_plots
project directory: /Users/sunilmd/Desktop/vscode/MATH-516/project-2-nikita_zhuo/analysis_and_plots

# Section 2: Exploratory Data Analysis

In [ ]:
#Look at the first few rows of the dataset
print("Dataset shape: {0}".format(df.shape)) #check the shape of the dataset

Dataset shape: (2736, 7)

In [13]:
df.head()

  person  day  session activity sex HF_type   HF_value
0     F1    1        1  sitting   F   HF_16  44.553187
1     F1    1        1  sitting   F    HF_7  75.400325
2     F1    1        1  sitting   F    HF_3  34.317035
3     F1    1        1  sitting   F    HF_5  59.724192
4     F1    1        1  sitting   F    HF_2  47.135426

In [ ]:
df.HF_type.unique()
#six different sensors

array(['HF_16', 'HF_7', 'HF_3', 'HF_5', 'HF_2', 'HF_8'], dtype=object)

In [72]:
df.activity.unique()

array(['sitting', 'standing', 'walking'], dtype=object)

In [73]:
df.sex.unique()

array(['F', 'M'], dtype=object)

In [74]:
print("Person IDs: {0}".format(df.groupby("person").count()))
#12 men, 12 women. 114 rows for each
#why do some hf values not go to 114? some missing values?

Person IDs:         day  session  activity  sex  HF_type  HF_value
person
F1      114      114       114  114      114       114
F10     114      114       114  114      114       114
F11     114      114       114  114      114       100
F12     114      114       114  114      114       113
F2      114      114       114  114      114       114
F3      114      114       114  114      114       114
F4      114      114       114  114      114       104
F5      114      114       114  114      114       111
F6      114      114       114  114      114       112
F7      114      114       114  114      114       114
F8      114      114       114  114      114       113
F9      114      114       114  114      114       113
M1      114      114       114  114      114       113
M10     114      114       114  114      114       114
M11     114      114       114  114      114       114
M12     114      114       114  114      114       114
M2      114      114       114  114      114       113
M3      114      114       114  114      114       104
M4      114      114       114  114      114        73
M5      114      114       114  114      114       104
M6      114      114       114  114      114       114
M7      114      114       114  114      114       114
M8      114      114       114  114      114       111
M9      114      114       114  114      114       114

In [75]:
print("Days: {0}".format(df.groupby(["session", "day"]).count())) 
#2 days, 4 sessions per day
#again some hf values dont go to 432, some missing values?

Days:              person  activity  sex  HF_type  HF_value
session day
1       1       432       432  432      432       408
        2       432       432  432      432       430
2       1       288       288  288      288       269
        2       144       144  144      144       142
3       1       432       432  432      432       402
        2       432       432  432      432       430
4       1       288       288  288      288       272
        2       288       288  288      288       285

In [76]:
print("Days: {0}".format(df[df.session==1][df.day==1].groupby(["session", "day", "person"]).count()))
#2 days, 4 sessions per day
#for session 1 day 1, for example, a few people dont have values - most prominently m4

Days:                     activity  sex  HF_type  HF_value
session day person
1       1   F1            18   18       18        18
            F10           18   18       18        18
            F11           18   18       18        15
            F12           18   18       18        18
            F2            18   18       18        18
            F3            18   18       18        18
            F4            18   18       18        15
            F5            18   18       18        18
            F6            18   18       18        18
            F7            18   18       18        18
            F8            18   18       18        18
            F9            18   18       18        18
            M1            18   18       18        18
            M10           18   18       18        18
            M11           18   18       18        18
            M12           18   18       18        18
            M2            18   18       18        18
            M3            18   18       18        15
            M4            18   18       18         6
            M5            18   18       18        15
            M6            18   18       18        18
            M7            18   18       18        18
            M8            18   18       18        18
            M9            18   18       18        18

/var/folders/w_/q48fhdx54pg9htd0jvq6mqqm0000gn/T/ipykernel_86461/3415428404.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print("Days: {0}".format(df[df.session==1][df.day==1].groupby(["session", "day", "person"]).count()))

In [77]:
df[df.person=="M4"]
#some values are missing...

     person  day  session  activity sex HF_type    HF_value
2052     M4    1        1   sitting   M   HF_16   29.783193
2053     M4    1        1   sitting   M    HF_7   92.417590
2054     M4    1        1   sitting   M    HF_3         NaN
2055     M4    1        1   sitting   M    HF_5         NaN
2056     M4    1        1   sitting   M    HF_2         NaN
...     ...  ...      ...       ...  ..     ...         ...
2161     M4    2        4  standing   M    HF_7  117.153552
2162     M4    2        4  standing   M    HF_3   73.995736
2163     M4    2        4  standing   M    HF_5   90.393427
2164     M4    2        4  standing   M    HF_2   31.816827
2165     M4    2        4  standing   M    HF_8   64.723730

[114 rows x 7 columns]

In [ ]:
Q0: are heat flow measures independent?

residual plot
x-axis = session
y-axis = residuals (for model guessing hf value)
row on grid = sensor
column on grid = activity
colors = person

#base model with all main effects, no interactions, no sex, no person
lm_base <- lm(heat_flow ~ session + activity + sensor + factor(day), data = df)

In [ ]:
lm_base <- lm(heat_flow ~ session + activity + sensor + factor(day), data = df)
df$resids <- residuals(lm_base)